FROM public.ecr.aws/docker/library/nginx:latest
COPY index.html /usr/share/nginx/html/index.html
COPY admin/index.html /usr/share/nginx/html/admin/index.html
COPY public/index.html /usr/share/nginx/html/public/index.html